from typing import Protocol, runtime_checkable
import myapp.db.model as dbmodel

@runtime_checkable
class ServiceInterface(Protocol):

    def init(self) -> None: ...

    def read_sysdate(self) -> str: ...

    def read_user(self, username: str) -> dbmodel.User: ...

    def read_user_session(self, session_id: str) -> dbmodel.Session | None: ...

    def read_all_session(self, session_id: str) -> list[dbmodel.Session]: ...

    def create_user(self, arg: dbmodel.CreateUserParams) -> dbmodel.User: ...

    def create_user_session(self, arg: dbmodel.CreateSessionParams) -> dbmodel.Session: ...

    def delete_user_session(self, session_id: str) -> None: ...
