from typing import Protocol, runtime_checkable

from myapp.db.model import CreateSessionParams, CreateUserParams, Session, User


@runtime_checkable
class DbHandler(Protocol):

    def init(self) -> None: ...

    def close(self) -> None: ...

    def read_sysdate(self) -> str: ...

    def read_user(self, username: str) -> User: ...

    def read_user_session(self, session_id: str) -> Session | None: ...

    def read_all_session(self) -> list[Session]: ...

    def create_user(self, arg: CreateUserParams) -> User: ...

    def create_user_session(self, arg: CreateSessionParams) -> Session: ...

    def delete_user_session(self, session_id: str) -> None: ...
